<?php

use Faker\Generator as Faker;

$factory->define(App\Application::class, function (Faker $faker) {
    return [
        'user_id' => $faker->randomElement(['1','2']),
        'class' => $faker->ean8(),
        'license' => $faker->ean8(),
        'fee' => $faker->randomFloat($nbMaxDecimals = NULL, $min = 0, $max = NULL),
        'address' => $faker->streetAddress(),
        'city' => $faker->city(),
        'state' => $faker->state(),
        'corporate_name' => $faker->company(),
        'corporate_address' => $faker->address(),
        'name_business_to_be_conducted' => $faker->company(),
        'business_phone' => $faker->phoneNumber(),
        'business_mobile' => $faker->phoneNumber(),
        'business_email' => $faker->email(),
        'president_name' => $faker->name(),
        'president_address' => $faker->address(),
        'president_phone' => $faker->phoneNumber(),
        'president_mobile' => $faker->phoneNumber(),
        'president_email' => $faker->email(),
        'vice_president_name' => $faker->name(),
        'vice_president_address' => $faker->address(),
        'vice_president_phone' => $faker->phoneNumber(),
        'vice_president_mobile' => $faker->phoneNumber(),
        'vice_president_email' => $faker->email(),    
        'secretary_name' => $faker->name(),
        'secretary_address' => $faker->address(),
        'secretary_phone' => $faker->phoneNumber(),
        'secretary_mobile' => $faker->phoneNumber(),
        'secretary_email' => $faker->email(),   
        'treasurer_name' => $faker->name(),
        'treasurer_address' => $faker->address(),
        'treasurer_phone' => $faker->phoneNumber(),
        'treasurer_mobile' => $faker->phoneNumber(),
        'treasurer_email' => $faker->email(),    
        'director_name' => $faker->name(),
        'director_address' => $faker->address(),
        'director_phone' => $faker->phoneNumber(),
        'director_mobile' => $faker->phoneNumber(),
        'director_email' => $faker->email(), 
        'vice_director_name' => $faker->name(),
        'vice_director_address' => $faker->address(),
        'vice_director_phone' => $faker->phoneNumber(),
        'vice_director_mobile' => $faker->phoneNumber(),
        'vice_director_email' => $faker->email(), 
        'date_incorporation' => $faker->dateTimeThisDecade($max = 'now', $timezone = null),
        'state_incorporation' => $faker->state(),
        'created_at' =>  $faker->dateTime(),
        'status' => $faker->randomElement(['incomplete', 'completed', 'processed', 'paid'])    
    ];
});
